[package]
name = "deduper"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
indicatif = "0.17.8"
rayon = "1.10.0"
rexif = "0.7.4"
thiserror = "1.0.64"
walkdir = "2.5.0"
xxhash-rust = { version = "0.8.12", features = ["xxh3"] }
